config/routes.rb
Rewards::Engine.routes.draw do
  root 'home#index'

  resources :bestowments, only: %i[new create]
end

app/models/rewards/application_record.rb
module Rewards
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/rewards/bestowment.rb
module Rewards
  class Bestowment < ApplicationRecord
    has_one :piece

    belongs_to :bestower, class_name: 'User', foreign_key: :bestower_id
    belongs_to :bestowed, class_name: 'User', foreign_key: :bestowed_id

    after_create :bestow_piece

    def bestow_piece
      create_piece(reward: bestowed.current_reward)
    end
  end
end

app/models/rewards/piece.rb
module Rewards
  class Piece < ApplicationRecord
    belongs_to :reward
    belongs_to :bestowment
    has_many :reward_pieces, through: :reward, source: :pieces

    enum identifier: %i[first_quarter
                        second_quarter
                        third_quarter
                        fourth_quarter]

    before_save :set_identifier

    after_create :complete_reward

    def set_identifier
      self.identifier = next_piece
    end

    def next_piece
      Piece.identifiers.key(reward_pieces.size)
    end

    def complete_reward
      reward.complete! if fourth_quarter?
    end
  end
end

app/models/rewards/reward.rb
module Rewards
  class Reward < ApplicationRecord
    belongs_to :user
    has_many :pieces

    enum state: %i[incomplete complete]
  end
end

app/controllers/rewards/application_controller.rb
module Rewards
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/rewards/bestowments_controller.rb
require_dependency "rewards/application_controller"

module Rewards
  class BestowmentsController < ApplicationController
    def new
      @bestowment = Rewards::Bestowment.new
    end

    def create
      @bestowment = Rewards::Bestowment.new(bestowment_params)
      @bestowment.bestower = current_user

      if @bestowment.save
        flash[:notice] = 'Bestowment created successfully!'
        redirect_to root_url
      else
        render :new
      end
    end

    def bestowment_params
      params.require(:bestowment).permit(:bestowed_id)
    end
  end
end

app/controllers/rewards/home_controller.rb
require_dependency "rewards/application_controller"

module Rewards
  class HomeController < ApplicationController
    def index
      @rewards = current_user.rewards
      @current_reward = current_user.current_reward
    end
  end
end

app/helpers/rewards/application_helper.rb
module Rewards
  module ApplicationHelper
  end
end

app/views/layouts/rewards/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rewards</title>
  <%= stylesheet_link_tag    "rewards/application", media: "all" %>
  <%= javascript_include_tag "rewards/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p><%= flash[:notice]%></p>
  <p><%= flash[:alert]%></p>
  <%= yield %>

</body>
</html>

app/views/rewards/bestowments/new.html.erb
<h1>New Bestowment</h1>

<%= form_with(model: @bestowment, data: { remote: false }) do |f| %>
  <%= f.label :user %>
  <%= f.collection_select(:bestowed_id,
                          current_user.teammates, :id, :full_name,
                          {},
                          { id: "bestowment_bestowed_id" }) %>

  <%= f.submit %>
<% end %>

app/views/rewards/home/index.html.erb
<h1>Rewards</h1>

<p>Current reward:</p>
<ul>
  <%= render @current_reward.pieces %>
</ul>

<ul>
  <%= render @rewards %>
</ul>

<%= link_to 'New Bestowment', new_bestowment_path %>

app/views/rewards/pieces/_piece.html.erb
<li>
  <%= piece.identifier %>
</li>

app/views/rewards/rewards/_reward.html.erb
<li>
  <p>State: <%= reward.state %></p>
  <p>Pieces: <%= reward.pieces.count %></p>
</li>